# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            sudeep.co
tagline:          'A Jekyll theme'
description:      'Data science enthusiast, aspiring entrepreneur, interested in AI, Machine Learning and NLP'
url:              http://sudeep.co
baseurl:          /

paginate:         5
excerpt_separator: <!--more-->

gems: [jekyll-gist, jekyll-paginate]
